Resources:
  WalletsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "customerId"
          "AttributeType": "S"
        - "AttributeName": "walletName"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "customerId"
          "KeyType": "HASH"
        - "AttributeName": "walletName"
          "KeyType": "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: "wallets"