@startuml

actor "Client" as client
participant "Website Add Cryptocurrency page" as apiGateway
participant "AddCryptocurrencyToWalletActivity" as addCryptocurrencyToWalletActivity
database "wallets" as wallets

title Add Cryptocurrency to Wallet

client -> apiGateway : Submit add cryptocurrency form
activate apiGateway

apiGateway -> addCryptocurrencyToWalletActivity : Send add cryptocurrency request
activate addCryptocurrencyToWalletActivity

addCryptocurrencyToWalletActivity -> wallets : save updated wallet cryptocurrencies map

@enduml
